# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.75

## Mod Properties
mod_id=i113w_camera_lib
mod_name=113's Camera Lib
mod_license=MIT
mod_version=2612-0.0.1-alpha1
mod_group_id=com.i113w
mod_authors=i113w
mod_description=A Lib that provides the RTS Style Camera System which is used by Better Mine Team.
